// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACarousel: typeof import('ant-design-vue/es')['Carousel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    App: typeof import('./src/App.vue')['default']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ChangeLocale: typeof import('./src/components/ChangeLocale.vue')['default']
    ChangeTheme: typeof import('./src/components/ChangeTheme.vue')['default']
    Footer: typeof import('./src/views/public/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Help: typeof import('./src/views/home/Help.vue')['default']
    Home: typeof import('./src/views/home/index.vue')['default']
    HomeCards: typeof import('./src/views/home/components/HomeCards.vue')['default']
    HomeCarousel: typeof import('./src/views/home/components/HomeCarousel.vue')['default']
    HomeHeader: typeof import('./src/views/home/components/HomeHeader.vue')['default']
    HomeHeaderFix: typeof import('./src/views/home/components/HomeHeaderFix.vue')['default']
    HomeIntroduction: typeof import('./src/views/home/components/HomeIntroduction.vue')['default']
    HomeNews: typeof import('./src/views/home/components/HomeNews.vue')['default']
    HomeTools: typeof import('./src/views/home/components/HomeTools.vue')['default']
    MainOut: typeof import('./src/views/main-out/index.vue')['default']
    PageNotFound: typeof import('./src/views/sys/exception/PageNotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/views/main-out/Test.vue')['default']
    Test1: typeof import('./src/views/ltgem/test1.vue')['default']
    Test2: typeof import('./src/views/ltgem/test2.vue')['default']
    Test3: typeof import('./src/views/ltgem/test3.vue')['default']
    Tmp: typeof import('./src/components/tmp.vue')['default']
  }
}
